=== hynnet/opennms-pmacct/src/main/castor/pmacct-datacollection-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://xmlns.opennms.org/xsd/config/pmacct-datacollection" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns2="http://www.w3.org/1999/xhtml" xmlns:ns="http://www.w3.org/2001/XMLSchema"
	xmlns:hfp="http://www.w3.org/2001/XMLSchema-hasFacetAndProperty" xmlns:pmacct-dc="http://xmlns.opennms.org/xsd/config/pmacct-datacollection">
	<annotation>
		<documentation>
			XML Schema for the pmacct-datacollection-config.xml configuration file.

			Collections:
			- As in SNMP data collection, multiple collections can be defined
			- RRD definition is defined here, by as with the other data collection
			configurations (SNMP, JMX) it should be moved to the package specification.
			- Multiple URIs can be defined and is synonymous with groups defined in
			SNMP data collection.
			URLs:
			- Initial use case for this collector's configuration is to support multiple schemes (i.e. http,
			(ftp, file, etc.) but initial use will be for http only and is configured by default.
			- URLs have many attributes (authority, scheme, user-agent, virtual-host, etc.)
			- URLs support query strings as well as post fields. 
    </documentation>
	</annotation>

	<element name="pmacct-datacollection-config">
		<annotation>
			<documentation>Top-level element for the datacollection-config.xml
				configuration file.</documentation>
		</annotation>

		<complexType>
			<sequence>
				<element ref="pmacct-dc:pmacct-collection" minOccurs="0" maxOccurs="unbounded" />
			</sequence>
			<attribute name="rrdRepository" type="string" use="required">
				<annotation>
					<documentation>full path to the RRD repository for collected SNMP data</documentation>
				</annotation>
			</attribute>
			<attribute name="pmacctPath" type="string" use="optional" default="/usr/bin/pmacct" />
		</complexType>
	</element>

	<element name="pmacct-collection">
		<complexType>
			<sequence>
				<element ref="pmacct-dc:rrd" minOccurs="1" maxOccurs="1" />
				<element ref="pmacct-dc:attributes" minOccurs="1" maxOccurs="1" />
			</sequence>
			<attribute name="name" type="string" use="optional" default="default" />
		</complexType>
	</element>

	<element name="attributes">
		<complexType>
			<sequence>
				<element ref="pmacct-dc:attrib" minOccurs="1" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<element name="attrib">
		<complexType>
			<attribute name="pmacct-options" type="string" />
			<attribute name="alias" type="string" use="required" />
			<attribute name="matches" type="string" />
			<attribute name="match-group" >
				<simpleType>
					<restriction base="int">
						<minInclusive value="1" />
					</restriction>
				</simpleType>
			</attribute>
			<attribute name="type" type="pmacct-dc:allowed-types" use="required" />
		</complexType>
	</element>

	<simpleType name="allowed-types">
		<annotation>
			<documentation>Collected data types: counter, gauge,
				timeticks, integer, octetstring, string. The SNMP type is mapped to
				one of two RRD supported data types COUNTER or GAUGE, or the
				string.properties file. The mapping is as follows: SNMP counter
				-&gt; RRD COUNTER; SNMP gauge, timeticks, integer, octetstring -&gt;
				RRD GAUGE; SNMP string -&gt; String properties file
      </documentation>
		</annotation>
		<restriction base="string">
			<pattern
				value="([Cc](ounter|OUNTER)(32|64)?|[Gg](auge|AUGE)(32|64)?|[Tt](ime|IME)[Tt](icks|ICKS)|[Ii](nteger|NTEGER)(32|64)?|[Oo](ctet|CTET)[Ss](tring|TRING))|[Ss](tring|TRING)" />
		</restriction>
	</simpleType>

	<element name="rrd">
		<annotation>
			<documentation>RRD parms</documentation>
		</annotation>
		<complexType>
			<sequence>
				<element maxOccurs="unbounded" minOccurs="1" name="rra">
					<annotation>
						<documentation>Round Robin Archive definitions</documentation>
					</annotation>

					<simpleType>
						<restriction base="string">
							<pattern value="RRA:(AVERAGE|MIN|MAX|LAST):.*" />
						</restriction>
					</simpleType>
				</element>
			</sequence>
			<attribute name="step" use="required">
				<annotation>
					<documentation>step size for the RRD</documentation>
				</annotation>

				<simpleType>
					<restriction base="int">
						<minInclusive value="1" />
					</restriction>
				</simpleType>
			</attribute>
		</complexType>
	</element>

</schema>

=== hynnet/opennms-pmacct/conf/opennms/pmacct-datacollection-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<pmacct-datacollection-config  
    xmlns:pmacct-dc="http://xmlns.opennms.org/xsd/config/pmacct-datacollection" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://xmlns.opennms.org/xsd/config/pmacct-datacollection http://www.opennms.org/xsd/config/pmacct-datacollection-config.xsd" 
    rrdRepository="/var/lib/opennms/rrd/snmp/" >
  <pmacct-collection name="pmacct-bandwidth">
    <rrd step="300">
      <rra>RRA:AVERAGE:0.5:1:2016</rra>
      <rra>RRA:AVERAGE:0.5:12:1488</rra>
      <rra>RRA:AVERAGE:0.5:288:366</rra>
      <rra>RRA:MAX:0.5:288:366</rra>
      <rra>RRA:MIN:0.5:288:366</rra>
    </rrd>
    <attributes>
        <attrib alias="pmacctInbound"  type="gauge" pmacct-options=" -c dst_host -N %h -p /var/lib/pmacct/in.pipe -r"/>
        <attrib alias="pmacctOutbound" type="gauge" pmacct-options=" -c src_host -N %h -p /var/lib/pmacct/out.pipe -r"/>
    </attributes>
  </pmacct-collection>
</pmacct-datacollection-config>
